version: '3'

services:
  bisabelajardb:
    image: postgres:13
    container_name: bisabelajardb
    environment:
      POSTGRES_USER: bisabelajar
      POSTGRES_PASSWORD: bisabelajar
    restart: unless-stopped
    volumes:
      - "./migrations/bisabelajar.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
    networks:
      - backend
  # jaeger:
  #   image: jaegertracing/all-in-one
  #   container_name: jaeger
  #   restart: unless-stopped
  #   ports:
  #     - 5775:5775/udp
  #     - 5778:5778
  #     - 6831:6831/udp
  #     - 6832:6832/udp
  #     - 9411:9411
  #     - 14268:14268
  #     - 16686:16686  
networks:
  backend:
    driver: bridge